services:
  - type: web
    name: tega-transit-api
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
        sync: false
      - key: NEXT_SUPABASE_CONNECTION_STRING
        sync: false
